//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPayment
    {
        public int id { get; set; }
        public Nullable<double> accountNumber { get; set; }
        public string accountName { get; set; }
        public Nullable<double> accountBalance { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<long> so_n { get; set; }
        public Nullable<long> so_e { get; set; }
        public string pri_key { get; set; }
        public string phone { get; set; }
    }
}
